import random
import time

def WhyareyoulonelyLMAO():
    wowzers = [
        "You're amazing!",
        "You have a great sense of humor!",
        "You're incredibly talented!",
        "You're a fantastic friend!",
        "You light up the room!",
        "You're doing a great job!",
        "You have a positive attitude!",
        "You're a true inspiration!",
        "You have a great smile!",
        "Your creativity knows no bounds!",
        "You're a great listener!",
        "You have a wonderful personality!",
        "You're so kind-hearted!",
        "You make everyone feel special!",
        "You have a knack for making people feel better!",
        "You're a breath of fresh air!",
        "You have a strong work ethic!",
        "You bring out the best in people!",
        "You have an amazing sense of style!",
        "Your energy is contagious!",
        "You're a problem solver!",
        "You have a heart of gold!",
        "You inspire others with your dedication!",
        "You have a great sense of adventure!",
        "You're a natural leader!",
        "Your enthusiasm is infectious!",
        "You have a talent for making people laugh!",
        "You're a true team player!",
        "You have a great sense of empathy!",
        "You always know how to brighten someone's day!",
        "You're incredibly thoughtful!",
        "You have a great way with words!",
        "You're always so encouraging!",
        "You have an eye for detail!",
        "You make every day better!",
        "You're a joy to be around!",
        "You have a remarkable ability to motivate others!",
        "You're a wonderful person inside and out!",
        "You make people feel appreciated!",
        "You're always so supportive!",
        "You have a calming presence!",
        "You're incredibly intelligent!",
        "You have a fantastic work ethic!",
        "You make every task enjoyable!",
        "You're an excellent communicator!",
        "You have a great sense of humor!",
        "You're a great problem solver!",
        "You have an amazing ability to connect with people!",
        "You’re a great source of positivity!",
        "You always bring your best to the table!",
        "You have a wonderful outlook on life!",
        "You're a true friend!",
        "You bring so much joy to others!",
        "You're incredibly reliable!",
        "You have a fantastic sense of timing!",
        "You're a true gem!",
        "You make things happen!",
        "You have a strong sense of integrity!",
        "You always see the best in people!",
        "You're a source of inspiration!",
        "You bring a lot of energy into the room!",
        "You're incredibly creative!",
        "You have a gift for making others feel good!",
        "You have a special way of making people smile!",
        "You're a shining star!",
        "You have a knack for making things happen!",
        "You have a great ability to handle challenges!",
        "You're a wonderful role model!",
        "You have an incredible attention to detail!",
        "You're a ray of sunshine!",
        "You bring positivity wherever you go!",
        "You're an amazing friend!",
        "You have a heart full of compassion!",
        "You're always so thoughtful!",
        "You make everyone's day brighter!",
        "You have a wonderful way of making people feel valued!",
        "You're incredibly gifted!",
        "You have a great talent for making people laugh!",
        "You have an amazing ability to uplift others!",
        "You're a true treasure!",
        "You have a great sense of humor!",
        "You always know how to put a smile on someone's face!",
        "You're a fantastic team player!",
        "You have a knack for making everything better!",
        "You have a wonderful ability to bring people together!",
        "You're a constant source of inspiration!",
        "You have a remarkable ability to stay positive!",
        "You're a brilliant thinker!",
        "You have a great way of making everyone feel included!",
        "You're an incredible listener!",
        "You bring so much joy into people's lives!",
        "You're always so considerate!",
        "You have a wonderful way of making others feel important!",
        "You're a beacon of light!",
        "You have a talent for making people feel special!",
        "You're a true ray of sunshine!",
        "You have a great ability to inspire others!",
        "You bring a lot of happiness to those around you!",
        "You're a fabulous person!",
        "You have a wonderful way of making things happen!",
        "You're a true delight!",
        "You have a gift for making people feel good about themselves!",
        "You're a great source of support!",
        "You have a fantastic ability to brighten someone's day!",
        "You're an amazing person!",
        "You have an incredible gift for bringing people together!",
        "You're a true asset!",
        "You have a wonderful ability to make everyone feel welcome!",
        "You're a shining example of kindness!",
        "You have a remarkable talent for making people feel appreciated!",
        "You're an absolute joy!",
        "You have a great sense of empathy and understanding!",
        "You're a true blessing!",
        "You have a wonderful way of lifting others up!",
        "You're an exceptional individual!",
        "You bring so much light into the world!",
        "You're a fantastic person with a big heart!",
        "You have an amazing ability to connect with people!",
        "You're a wonderful source of positivity!"
    ]
    return random.choice(wowzers)

def main():
    print("Because you're lonely :> ")
    while True:
        print(WhyareyoulonelyLMAO())
        time.sleep(5)  # delay for the next one

if __name__ == "__main__":
    main()
